import '../lib/routes/routes'

import './html/layout.html'
import './html/sidebar.html'
import './html/home.html'
import './html/login.html'
import './html/signup.html'
import './html/profile.html'
import './html/rankings.html'
import './html/search.html'
import './html/jokeForm.html'

import './js/signup'
import './js/siderbar'
import './js/login'
import './js/profile'
import './js/jokes'
import './js/rankings'
import './js/search'
import './js/jokeForm'

import '../lib/sub'